export const THEM_CAPNHAT_SINH_VIEN = 'THEM_CAPNHAT_SINH_VIEN'
export const XOA_SINH_VIEN = 'THEM_SINH_VIEN'
export const LAY_SINH_VIEN = 'LAY_SINH_VIEN'
export const SEARCH_SINH_VIEN = 'SEARCH_SINH_VIEN'